### ISSUE TITLE
Exception on default print to console

### ISSUE THREAD

**Issue by xfoggi** [MarketSquare/robotframework-sherlock#63]
Command: `python3 -m sherlock --report html` runs fine and creates a report. But using the default console output on the same repository failed with an exception below.
`
czsfpgspri69397:XXX-testing-new fogl$ python3 -m sherlock
Sherlock analysis of Robot Framework code:

Using /Users/XXX/Documents/PROJECTS/XXX-testing-new as source repository
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/sherlock/__main__.py", line 5, in <module>
    run_cli()
  File "/usr/local/lib/python3.9/site-packages/sherlock/__init__.py", line 19, in run_cli
    raise err
  File "/usr/local/lib/python3.9/site-packages/sherlock/__init__.py", line 9, in run_cli
    runner.run()
  File "/usr/local/lib/python3.9/site-packages/sherlock/core.py", line 41, in run
    self.report()
  File "/usr/local/lib/python3.9/site-packages/sherlock/core.py", line 51, in report
    print_report(tree, self.config.log_output)
  File "/usr/local/lib/python3.9/site-packages/sherlock/report/print.py", line 70, in print_report
    log_directory(directory, tree)
  File "/usr/local/lib/python3.9/site-packages/sherlock/report/print.py", line 51, in log_directory
    log_directory(resource, branch)
  File "/usr/local/lib/python3.9/site-packages/sherlock/report/print.py", line 51, in log_directory
    log_directory(resource, branch)
  File "/usr/local/lib/python3.9/site-packages/sherlock/report/print.py", line 51, in log_directory
    log_directory(resource, branch)
  File "/usr/local/lib/python3.9/site-packages/sherlock/report/print.py", line 54, in log_directory
    keywords = [kw for kw in resource.keywords]
TypeError: 'NoneType' object is not iterable
`

**Comment by bhirsz** [comment]
Thanks for the report - I can also reproduce it (only on some repositories, for example on Browser atests).
