### ISSUE TITLE
Sherlock fails to parse value of dict with equal sign

### ISSUE THREAD

**Issue by nicolasbillamboz-flowbird** [MarketSquare/robotframework-sherlock#92]
Let's consider the following test:
```robotframework
*** Variables ***
&{MY_DICT}=     key=string with = sign

*** Test Cases ***
My test
    Log    ${MY_DICT}
``` 
When I run sherlock against the folder containing this file, I get the following error:
```
Sherlock analysis of Robot Framework code:

Using <my_root_project>/sandbox as source repository
Traceback (most recent call last):
  File "<my_root_project>/.venv/bin/sherlock", line 8, in <module>
    sys.exit(run_cli())
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/__init__.py", line 19, in run_cli
    raise err
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/__init__.py", line 9, in run_cli
    runner.run()
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/core.py", line 31, in run
    tree = self.map_resources_for_path(root)
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/core.py", line 58, in map_resources_for_path
    tree = Tree.from_directory(path=root, gitignore=self.config.default_gitignore)
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/model.py", line 359, in from_directory
    tree.children.append(Resource(child))
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/model.py", line 307, in __init__
    visitor.visit(model)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/model.py", line 172, in visit_Variable
    self.variables[node.name] = self.set_dict(node.value)
  File "<my_root_project>/.venv/lib/python3.8/site-packages/sherlock/model.py", line 178, in set_dict
    key, val = value.split("=") if "=" in value else (value, "")
ValueError: too many values to unpack (expected 2)
Fatal exception occurred. You can create an issue at https://github.com/bhirsz/robotframework-sherlock/issues . Thanks!
```
**Environment**

- OS: Ubuntu 20.04
- Python: 3.8.10
- RobotFramework: 6.1
- robotframework-sherlock: 0.2.0

In addition, when using sherlock on a folder containing multiple files, it would be wise to report the name of the file containing the issue in order to identify quickly the problem.

**Comment by bhirsz** [comment]
Thanks for the report. Handling of the variables is really primitive here, I will replace it with proper parsing.

And very good idea with logging the file where exception occurred. It could be also useful for Robotidy and Robocop (for unexpected exceptions). I need to investigate what would be the best way to do it. As intermediate solution I can add verbose mode to Sherlock that will print every processed file so it could be used to debug what caused exception.

**Comment by nicolasbillamboz-flowbird** [comment]
Why not surrounding the statement `visitor.visit(model)` with a try/except block in `Resource.__init__` method, and log the filename with traceback if an error occurs?

**Comment by bhirsz** [comment]
Fixed in linked PR. It will be part of the next release (0.3) which should be out by the end of next week.

The solution is bit of workaround, I fixed the issue (and also implemented logging the source path if there is exception) but this part will need to be rewritten anyway. Hovewer I have added this case to our regression tests so it should be also fine after future refactors.
